apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-api-deployment
  labels:
    app: qa-api
spec:
  selector:
    matchLabels:
      app: qa-api
  template:
    metadata:
      labels:
        app: qa-api
    spec:
      containers:
        - name: qa-api
          image: qa-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7777
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: qa-app-database-cluster-app
                  key: username
                  optional: false
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: qa-app-database-cluster-app
                  key: password
                  optional: false
            - name: PGHOST
              value: 'qa-app-database-cluster-rw'
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: 'app'
            - name: DENO_DIR
              value: '/app-cache'
