version: '3.4'

volumes:
  astro_node_modules:

services:
  todo-api:
    build:
      context: todo-api
      dockerfile: Dockerfile.prod
    image: todo-api
    restart: 'on-failure'
    volumes:
      - ./todo-api/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - flyway
      - redis
    env_file:
      - project.env
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: '5s'
        max_attempts: 5
        window: '30s'

  todo-ui:
    build:
      context: todo-ui
      dockerfile: Dockerfile.prod
    image: todo-ui
    restart: 'on-failure'
    volumes:
      - ./todo-ui/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - todo-api
    deploy:
      restart_policy:
        condition: on-failure
        delay: '5s'
        max_attempts: 5
        window: '30s'

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379

  database:
    container_name: database-server
    image: postgres:14.1
    restart: 'unless-stopped'
    volumes:
      - ./production-database-data:/var/lib/postgresql/data
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
    profiles:
      - migrate

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-api
      - todo-ui
    ports:
      - 7800:7800
