version: '3.4'

volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - qa-api
      - qa-ui
    ports:
      - 7800:7800

  qa-api:
    build:
      context: qa-api
      dockerfile: Dockerfile.prod
    image: qa-api
    restart: 'on-failure'
    volumes:
      - ./qa-api/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: '5s'
        max_attempts: 5
        window: '30s'

  qa-ui:
    build:
      context: qa-ui
      dockerfile: Dockerfile.prod
    image: qa-ui
    restart: 'on-failure'
    volumes:
      - ./qa-ui/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - qa-api
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: '5s'
        max_attempts: 5
        window: '30s'

  llm-api:
    build:
      context: llm-api
      dockerfile: Dockerfile.prod
    image: llm-api
    restart: 'on-failure'
    expose:
      - 7000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: '5s'
        max_attempts: 5
        window: '30s'

  database:
    container_name: database-server-dab-p2-56a1311e-df76-4b02-8db8-99f2bd86fafa
    image: postgres:14.1
    restart: 'on-failure'
    env_file:
      - project.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: '5s'
        max_attempts: 5
        window: '30s'

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  e2e-playwright:
    entrypoint: '/bin/true'
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
      - qa-api
      - qa-ui
      - llm-api
      - redis
      - database
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    depends_on:
      - nginx
      - qa-api
      - qa-ui
      - llm-api
      - database
    deploy:
      restart_policy:
        condition: on-failure
        delay: '5s'
        max_attempts: 5
        window: '30s'
